-- Criando tabelas

CREATE TABLE IF NOT EXISTS USERS (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(120) NOT NULL,
   EMAIL			VARCHAR(255) NOT NULL,
   PASSWORD			VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS EXPENSE_GROUP (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(60) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   USER_ID			INT8 NOT null 
);


CREATE TABLE IF NOT EXISTS ACCOUNTS (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(60) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   USER_ID			INT8 NOT NULL,
   BALANCE			FLOAT8 NOT null,
   STATUS			VARCHAR(20)
);


CREATE TABLE IF NOT EXISTS CATEGORIES (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(60) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   CATEGORY_TYPE	VARCHAR(20) NOT NULL,
   USER_ID			INT8 NOT NULL
);


CREATE TABLE IF NOT EXISTS CARDS (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(40) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   ACCOUNT_ID		INT8 NOT NULL,
   USER_ID			INT8 NOT NULL,
   CLOSING_DATE		INT2 NOT NULL,
   CARD_TYPE_ID		INT8 NOT NULL
);


CREATE TABLE IF NOT EXISTS CARD_TYPE (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(20) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   ACCOUNT_ID		INT8 NOT NULL,
   USER_ID			INT8 NOT NULL
);


CREATE TABLE IF NOT EXISTS PAYMENT_TYPE (
   ID				INT8 NOT NULL PRIMARY KEY,
   NAME				VARCHAR(60) NOT NULL,
   DESCRIPTION		VARCHAR(255) NOT NULL,
   USER_ID			INT8 NOT NULL
);


CREATE TABLE IF NOT EXISTS EXPENSES (
   ID					INT8 NOT NULL PRIMARY KEY,
   TITLE				VARCHAR(60) NOT NULL,
   DESCRIPTION			VARCHAR(255) NOT NULL,
   STATUS				VARCHAR(20) not null,
   VALUE				FLOAT8 NOT NULL,
   PAID_VALUE			FLOAT8 NOT NULL,
   PAYMENT_DATE			TIMESTAMP NOT NULL,
   PAYMENT_DUE_DATE		TIMESTAMP NOT NULL,
   PURCHASE_DATE		TIMESTAMP NOT NULL,
   INSTALLMENT			INT8 NOT NULL,
   TOTAL_INSTALMENTS	INT8 NOT NULL,
   PAYMENT_TYPE_ID		INT8 NOT NULL,
   ACCOUNT_ID			INT8 NOT NULL,
   CARD_ID				INT8 not null,
   USER_ID				INT8 NOT NULL,
   EXPENSE_GROUP_ID		INT8,
   CATEGORY_ID			INT8
);


CREATE TABLE IF NOT EXISTS INCOMES (
   ID					INT8 NOT NULL PRIMARY KEY,
   TITLE				VARCHAR(60) NOT NULL,
   DESCRIPTION			VARCHAR(255) NOT NULL,
   VALUE				FLOAT8 NOT NULL,
   PAYMENT_DATE			TIMESTAMP NOT NULL,
   PAYMENT_TYPE_ID		INT8 NOT NULL,
   ACCOUNT_ID			INT8 NOT NULL,
   USER_ID				INT8 NOT NULL,
   CATEGORY_ID			INT8 NOT NULL
);

-- Criando sequences

CREATE SEQUENCE IF NOT EXISTS SEQ_USERS 		INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EXPENSE_GROUP INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_ACCOUNTS 		INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CATEGORIES 	INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CARDS 		INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_CARD_TYPE 	INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_PAYMENT_TYPE 	INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EXPENSES 		INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_INCOMES 		INCREMENT 1 START 1;

-- configurando chaves estrangeiras

ALTER TABLE EXPENSE_GROUP ADD CONSTRAINT FK_EXPENSE_GROUP FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNTS FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE CATEGORIES ADD CONSTRAINT FK_CATEGORIES FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE CARDS ADD CONSTRAINT FK_CARDS FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE CARDS ADD CONSTRAINT FK_CARDS_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE CARDS ADD CONSTRAINT FK_CARDS_CARD_TYPE_ID FOREIGN KEY (CARD_TYPE_ID) REFERENCES CARD_TYPE (ID);

ALTER TABLE CARD_TYPE ADD CONSTRAINT FK_CARD_TYPE_ACC_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE CARD_TYPE ADD CONSTRAINT FK_CARD_TYPE_USR_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE PAYMENT_TYPE ADD CONSTRAINT FK_PAYMENT_TYPE_USR_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID);

ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_PYMT_TP FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE (ID);
ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_ACC_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_USR_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_EXP_GP FOREIGN KEY (EXPENSE_GROUP_ID) REFERENCES EXPENSE_GROUP (ID);
ALTER TABLE EXPENSES ADD CONSTRAINT FK_EXPENSES_CAT_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID);

ALTER TABLE INCOMES ADD CONSTRAINT FK_INCOMES_PYMT_TP FOREIGN KEY (PAYMENT_TYPE_ID) REFERENCES PAYMENT_TYPE (ID);
ALTER TABLE INCOMES ADD CONSTRAINT FK_INCOMES_ACC_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID);
ALTER TABLE INCOMES ADD CONSTRAINT FK_INCOMES_USR_ID FOREIGN KEY (USER_ID) REFERENCES USERS (ID);
ALTER TABLE INCOMES ADD CONSTRAINT FK_INCOMES_CAT_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID);






















